### ISSUE TITLE
monterey wifi 不能使用

### ISSUE THREAD

**Issue by zkzhao** [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH#1]
请问大佬怎么才能驱动wifi

**Comment by Fu-Yuxuan-hub** [comment]
您是什么网卡

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zhenkaiZhao ***@***.***>
发送时间: Sunday, April 3, 2022 9:26:07 PM
收件人: Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH] monterey wifi 不能使用 (Issue #1)


请问大佬怎么才能驱动wifi

―

**Comment by Stick-Study** [comment]
> 请问大佬怎么才能驱动wifi

您使用的网卡型号是什么

**Comment by zkzhao** [comment]
ASUS TUF GAMING B460M PLUS (WI-FI)   主板自带的无线网卡 。另外cpu是i5-10400

**Comment by Stick-Study** [comment]
> ASUS TUF GAMING B460M PLUS (WI-FI)   主板自带的无线网卡 。另外cpu是i5-10400

*如果您的系统为macOS Big Sur及以下，可使用AirportItlwm.kext驱动 访问此处：https://github.com/OpenIntelWireless/itlwm

*如果您的系统为macOS Monterey 则该网卡无法被驱动，请更换博通网卡

*希望此回复对您有帮助

**Comment by zkzhao** [comment]
谢谢，明白了

**Comment by zkzhao** [comment]
> 

[AirportItlwm_v2.1.0_stable_Monterey.kext.zip](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.1.0/AirportItlwm_v2.1.0_stable_Monterey.kext.zip)

最新版本的驱动已经可以支持Monterey AX200，亲测可用，感谢大佬提示。
