### ISSUE TITLE
0.8

### ISSUE THREAD

**Issue by Scorpiohao** [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH#11]

**Comment by Scorpiohao** [comment]
0.8.8-->0.9.3  efi直接替换？ 6650xt

**Comment by Scorpiohao** [comment]
大佬 又来烦你了哈哈哈

**Comment by Scorpiohao** [comment]
或者说0.8.8直接升级14.0系统会有问题不

**Comment by Stick-Study** [comment]
> 0.8.8-->0.9.3 efi直接替换？ 6650xt

替换kext, efi驱动, config就好了

必须要升级到 0.9.3 及更新的 OpenCore 版本。

如果你有免驱无线网卡，强烈不建议升级到 macOS Sonoma
