### ISSUE TITLE
睡眠之后网卡也彻底睡死了，需要使用有线设备才能唤醒

### ISSUE THREAD

**Issue by Today-fine** [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH#3]

**Comment by Stick-Study** [comment]
您USB定制时，是否将蓝牙设置为内建(internal)

**Comment by Today-fine** [comment]
实在不好意思，自己折腾了一天之后发现是网卡的问题。目前推断是电脑睡眠之后网卡也睡死了。USB定制改到内建了，USB总线也看到94360CD网卡的总线了，之后用另一块94360CD测试是OK的，就这样推断到网卡上了，实在不好意思
