### ISSUE TITLE
6500XT 10700核显和独显如何更改config文件

### ISSUE THREAD

**Issue by Scorpiohao** [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH#6]
大佬好，6500xt和10700核显 的config可以用吗？需要做那些修改呢

**Comment by Stick-Study** [comment]
很抱歉，RX6500XT无法被驱动

**Comment by Scorpiohao** [comment]
打错了是6650xt在 2023年1月14日，18:36，杆杆只爱学习 ***@***.***> 写道：﻿
很抱歉，RX6500XT无法被驱动

**Comment by Stick-Study** [comment]
你先直接安装，用[EFI_iGPU+dGPU.RX5500_and_newer.zip](https://github.com/Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH/releases/download/v0.8.8/EFI_iGPU+dGPU.RX5500_and_newer.zip)
然后截一张win下设备管理器-显示适配器-显卡右键-属性-详细信息，发上来

**Comment by Scorpiohao** [comment]
刘东浩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月14日(星期六) 晚上7:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH] 6500XT 10700核显和独显如何更改config文件 (Issue #6)





 
你先直接安装，用EFI_iGPU+dGPU.RX5500_and_newer.zip
 然后截一张win下设备管理器-显示适配器-显卡右键-属性-详细信息，发上来

**Comment by Stick-Study** [comment]
看不到发的任何东西

**Comment by Scorpiohao** [comment]
&nbsp;


刘东浩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月14日(星期六) 晚上9:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH] 6500XT 10700核显和独显如何更改config文件 (Issue #6)





 
看不到发的任何东西

**Comment by Scorpiohao** [comment]
现在是报错：OCB: Loadinage failed - Unsupported

**Comment by Stick-Study** [comment]
![截屏2023-01-14 21 29 15](https://user-images.githubusercontent.com/74492520/212474237-dc055d72-10d1-4679-9f89-43f58a9ef478.png)

请使用GitHub网页或者GitHub客户端上传

**Comment by Stick-Study** [comment]
> 现在是报错：OCB: Loadinage failed - Unsupported

你是使用com.apple.recovery.boot安装的嘛

**Comment by Scorpiohao** [comment]
![屏幕截图 2023-01-14 213200](https://user-images.githubusercontent.com/78369728/212474339-e45e36e0-f0fd-4f11-b0c7-0c6ef410c6f2.png)

**Comment by Scorpiohao** [comment]
![a7a1dbc3faa837a5c8020b443bd7275](https://user-images.githubusercontent.com/78369728/212474355-18280815-0f89-4f74-b4bb-31ec3e48307e.jpg)

**Comment by Stick-Study** [comment]
> ![屏幕截图 2023-01-14 213200](https://user-images.githubusercontent.com/78369728/212474339-e45e36e0-f0fd-4f11-b0c7-0c6ef410c6f2.png)

属性选位置路径

**Comment by Scorpiohao** [comment]
我是下载的带ac引导的镜像然后 通过TransMac u盘制作工具搞得

**Comment by Scorpiohao** [comment]
![屏幕截图 2023-01-14 213457](https://user-images.githubusercontent.com/78369728/212474533-9cfe8b6d-6ee3-4a46-baee-f5c6a186f87d.png)

**Comment by Scorpiohao** [comment]
PCI\VEN_1002&DEV_73EF&SUBSYS_05E31043&REV_C1\6&2E908885&0&00000008

**Comment by Stick-Study** [comment]
> 我是下载的带ac引导的镜像然后 通过TransMac u盘制作工具搞得
你要装什么系统

**Comment by Stick-Study** [comment]
> PCI\VEN_1002&DEV_73EF&SUBSYS_05E31043&REV_C1\6&2E908885&0&00000008

![image](https://user-images.githubusercontent.com/74492520/212474690-e2c665bd-3835-48ba-bc72-43eb73838276.png)
应该是这样的一张图

**Comment by Scorpiohao** [comment]
macOS Ventura 13.0.1 (22A400) With OpenCore 0.8.6 and winPE.dmg

**Comment by Scorpiohao** [comment]
就是这个镜像文件 mac13.0.1的版本

**Comment by Scorpiohao** [comment]
![屏幕截图 2023-01-14 214005](https://user-images.githubusercontent.com/78369728/212474755-f155c09e-66ba-4b6b-ae9b-34d2d943cc35.png)

**Comment by Scorpiohao** [comment]
是不是我下载的镜像文件有问题呢

**Comment by Stick-Study** [comment]
> 是不是我下载的镜像文件有问题呢

用etcher重写一下试试

**Comment by Scorpiohao** [comment]
显卡的位置路径这个是对应的吗 config文件需要修改吗？

**Comment by Scorpiohao** [comment]
我一开始用的etcher 写完之后 验证失败 总是写入失败 那就是镜像的问题吧？ 我以为是工具的问题 就换了一个u盘制作的工具

**Comment by Stick-Study** [comment]
> 我一开始用的etcher 写完之后 验证失败 总是写入失败 那就是镜像的问题吧？ 我以为是工具的问题 就换了一个u盘制作的工具

验证失败不用管，验一下镜像md5

**Comment by Scorpiohao** [comment]
![屏幕截图 2023-01-14 214605](https://user-images.githubusercontent.com/78369728/212475085-108ae46c-cd95-4890-a9cb-e7e72ebe2b07.png)

**Comment by Scorpiohao** [comment]
config文件我把这个改了

**Comment by Stick-Study** [comment]
> ![屏幕截图 2023-01-14 214605](https://user-images.githubusercontent.com/78369728/212475085-108ae46c-cd95-4890-a9cb-e7e72ebe2b07.png)

[SSDT-6650XT-73EF-GPU-SPOOF.aml.zip](https://github.com/Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH/files/10417459/SSDT-6650XT-73EF-GPU-SPOOF.aml.zip)
用这个替换原来的

**Comment by Scorpiohao** [comment]
还有 用etcher写入的时候 可以用原版镜像吗就是 不带引导的

**Comment by Stick-Study** [comment]
![截屏2023-01-14 21 54 38](https://user-images.githubusercontent.com/74492520/212475434-cd43a333-b138-4300-80a0-541741fa70c7.png)
因为他们的ACPI路径不同。你的是_SB_.PCI0.PEG0.PEGP
这里只看acpi部分，pci部分省略

**Comment by Scorpiohao** [comment]
所以说那个得根据路径改

**Comment by Scorpiohao** [comment]
![屏幕截图 2023-01-14 215625](https://user-images.githubusercontent.com/78369728/212475503-c6eefd04-98db-424e-97c7-e90b0624a564.png)

**Comment by Stick-Study** [comment]
> 

可以直接用在线恢复`com.apple.recovery.boot`

**Comment by Stick-Study** [comment]
我给你传一个

**Comment by Scorpiohao** [comment]
![屏幕截图 2023-01-14 220141](https://user-images.githubusercontent.com/78369728/212475729-0275a912-6e13-4e0f-b388-8de24fc6ca0d.png)

**Comment by Scorpiohao** [comment]
是通过这个吗？

**Comment by Stick-Study** [comment]
https://www.123pan.com/s/UztA-ohpN
格式化U盘为Fat32
![截屏2023-01-14 22 05 04](https://user-images.githubusercontent.com/74492520/212475913-7b6c2933-f3e8-4cda-805f-149ca28bc259.png)

**Comment by Scorpiohao** [comment]
![屏幕截图 2023-01-14 220900](https://user-images.githubusercontent.com/78369728/212476090-66039daa-2564-4fdc-852a-c805664e241c.png)

**Comment by Scorpiohao** [comment]
efi文件和com文件夹还是都是放在esp下面吗？

**Comment by Stick-Study** [comment]
> efi文件和com文件夹还是都是放在esp下面吗？

不用，放在F盘即可

**Comment by Scorpiohao** [comment]
了解了  感谢  我先试试吧 再 config文件除了 aml文件需要改动 其他设置是不是不需要改了呢

**Comment by Scorpiohao** [comment]
了解了  感谢  我先试试吧 再有 config文件除了 aml文件需要改动 其他设置是不是不需要改了呢

**Comment by Stick-Study** [comment]
> 

你的网卡是什么

**Comment by Scorpiohao** [comment]
没有无线网卡  还没买呢

**Comment by Stick-Study** [comment]
> 没有无线网卡 还没买呢

那就不需要任何更改了

**Comment by Scorpiohao** [comment]
![屏幕截图 2023-01-14 221722](https://user-images.githubusercontent.com/78369728/212476525-91db8187-546a-409f-9fd6-ad15c08db2ff.png)

**Comment by Scorpiohao** [comment]
这个我也改了 不是很清楚这个是啥0.0

**Comment by Scorpiohao** [comment]
是不是没必要改呢0.0

**Comment by Stick-Study** [comment]
> 这个我也改了 不是很清楚这个是啥0.0
> 
> 

从Radeon 7开始，macOS下就没有AMD独显温度显示了，这个就是温度传感器

**Comment by Scorpiohao** [comment]
哦哦 
![屏幕截图 2023-01-14 222310](https://user-images.githubusercontent.com/78369728/212476732-d7de4f9b-560e-40a8-8683-9b2e459c2174.png)

**Comment by Scorpiohao** [comment]
还有这个地方 我改成Disable了 之前是default

**Comment by Scorpiohao** [comment]
default 的话会卡代码 开机的时候 提示

**Comment by Stick-Study** [comment]
disabled可能就不会收到系统更新了

**Comment by Scorpiohao** [comment]
嗯嗯

**Comment by Stick-Study** [comment]
卡什么代码

**Comment by Scorpiohao** [comment]
![0b8b43e46ddb8f3f8ece7a01be9f046](https://user-images.githubusercontent.com/78369728/212476890-3b6738d9-bdbf-4df2-939f-6bf8bdbb0d58.jpg)

**Comment by Stick-Study** [comment]
这是镜像的锅，验证文件没有正确识别到

**Comment by Stick-Study** [comment]
`BaseSystem.chunklist`就是一个验证文件

**Comment by Scorpiohao** [comment]
是把 那就是了 哎 我先试试这个在线回复的方法

**Comment by Scorpiohao** [comment]
好的

**Comment by Scorpiohao** [comment]
K可以进入安装界面了 但是需要联网  提示我没联网

**Comment by Scorpiohao** [comment]
我是有线直接连接的 应该没问题呀

**Comment by Stick-Study** [comment]
> 我是有线直接连接的 应该没问题呀

抱歉，我忘记放驱动了

**Comment by Stick-Study** [comment]
[EFI.zip](https://github.com/Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH/files/10417961/EFI.zip)

**Comment by Scorpiohao** [comment]
这个是改动过后吗

**Comment by Stick-Study** [comment]
> 这个是改动过后吗

对

**Comment by Scorpiohao** [comment]
aml
是不是也得替换一下

**Comment by Stick-Study** [comment]
我换完了

**Comment by Stick-Study** [comment]
把那两个amd温度驱动也启用了

**Comment by Scorpiohao** [comment]
好的  那我改一下三码就行了把

**Comment by Scorpiohao** [comment]
感谢

**Comment by Stick-Study** [comment]
> 好的  那我改一下三码就行了把

对

**Comment by Stick-Study** [comment]
如果二阶段报未能安装所需的固件更新，启用config.plist — PlatformInfo — Generic - AdviseFeatures；

**Comment by Scorpiohao** [comment]
您好 安装完成了。但是有个小问题 每次开机都要设别一下键盘 是不是usb3.0的原因 这个的话需要改动config对应的哪里呢

**Comment by Stick-Study** [comment]
> 

你定制USB了嘛
推荐把键鼠插在2.0上并在定制USB是内建

**Comment by Scorpiohao** [comment]
![截屏2023-01-16 19 21 58](https://user-images.githubusercontent.com/78369728/212666816-da891e4c-8613-4d73-970b-cd41e2ab7d39.png)

**Comment by Scorpiohao** [comment]
定制导出的这些要替换掉efi文件里的吗？

**Comment by Stick-Study** [comment]
替换<USBPorts.kext>就可以

**Comment by Scorpiohao** [comment]
![截屏2023-01-16 19 24 20](https://user-images.githubusercontent.com/78369728/212667223-08682eff-b43b-4fef-a805-0a3ea173d318.png)

**Comment by Scorpiohao** [comment]
我是通过这个软件改的

**Comment by Scorpiohao** [comment]
那只换kext的话 config文件也不需要改了就对吧

**Comment by Stick-Study** [comment]
> 那只换kext的话 config文件也不需要改了就对吧
> 
> 

对
