### ISSUE TITLE
关于在线安装黑苹果的网络问题

### ISSUE THREAD

**Issue by rianlu** [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH#7]
我的配置是：
i5-10500+ASUS TUF GAMING B460M-PLUS (WI-FI)重炮手主板，使用核显和自带无线网卡

问题：按照教程制作好在线安装黑苹果的U盘，但是在安装界面无法继续，即使接上有线网络还是无法连接到互联网
解决办法：我后来在Windows下使用VMware安装Mac虚拟机制作了离线安装的U盘才解决
不知道是不是我少了什么步骤导致我有线网络无法使用

其他问题：我安装的是Monterey，都能够正常使用，然后当我升级到Ventura后，蓝牙和网卡驱动就都失效了，重新更新驱动也没用，不知道是不是我哪里操作不当，我也是刚玩黑苹果没多久😂

**Comment by Stick-Study** [comment]
感觉应该是网卡驱动没有加载，把以下的部分截图看看吧
（PS.如果您是16G内存及以上且在 macOS 13.3 可能会因为AppleVTD而导致网卡无法驱动）
![截屏2023-04-20 22 33 40](https://user-images.githubusercontent.com/74492520/233399421-32be1491-bb2f-449a-b893-f3f0633b7fa5.png)

![截屏2023-04-20 22 32 35](https://user-images.githubusercontent.com/74492520/233399412-e53e3e4c-8a7a-474f-ae20-a73bb1ed9bcf.png)

![截屏2023-04-20 22 32 10](https://user-images.githubusercontent.com/74492520/233399383-2fd4ce73-d8cf-4abe-a25c-8fab56212986.png)
![截屏2023-04-20 22 32 23](https://user-images.githubusercontent.com/74492520/233399402-c5b53ba8-86ee-44b9-acfd-606ebbcdb17d.png)

**Comment by rianlu** [comment]
> 感觉应该是网卡驱动没有加载，把以下的部分截图看看吧 （PS.如果您是16G内存及以上且在 macOS 13.3 可能会因为AppleVTD而导致网卡无法驱动） ![截屏2023-04-20 22 33 40](https://user-images.githubusercontent.com/74492520/233399421-32be1491-bb2f-449a-b893-f3f0633b7fa5.png)
> 
> ![截屏2023-04-20 22 32 35](https://user-images.githubusercontent.com/74492520/233399412-e53e3e4c-8a7a-474f-ae20-a73bb1ed9bcf.png)
> 
> ![截屏2023-04-20 22 32 10](https://user-images.githubusercontent.com/74492520/233399383-2fd4ce73-d8cf-4abe-a25c-8fab56212986.png) ![截屏2023-04-20 22 32 23](https://user-images.githubusercontent.com/74492520/233399402-c5b53ba8-86ee-44b9-acfd-606ebbcdb17d.png)

我确实是16g的内存，目前我的系统是Mac OS12，之前我是直接从12升级到13的，不知道是不是因为从12在线升级到13造成无法驱动（之前升级的时候登了Apple ID但忘了生成序列号）

**Comment by rianlu** [comment]
@Fu-Yuxuan-hub 这是我目前正在使用的配置
![image](https://user-images.githubusercontent.com/42767582/233413446-82e433a5-a33c-4f9f-9168-e71fd6b564d0.png)
![image](https://user-images.githubusercontent.com/42767582/233412374-7fb0cdf6-67b5-4a8a-b209-3dd0f519028c.png)
![image](https://user-images.githubusercontent.com/42767582/233413122-5fbfcde8-d6ee-4383-afb0-0514e8f9409c.png)
![image](https://user-images.githubusercontent.com/42767582/233413213-0280a34c-93b6-4b5d-b385-7e1190dcfd2a.png)
![image](https://user-images.githubusercontent.com/42767582/233413310-38f37e74-2a9c-4a86-9243-3c9021125be2.png)

**Comment by Stick-Study** [comment]
编译了一套最新的 Intel 网卡驱动，适用于 macOS Ventura，您可以试试
[Wi-Fi.zip](https://github.com/Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH/files/11301114/Wi-Fi.zip)
[Bluetooth.zip](https://github.com/Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH/files/11301115/Bluetooth.zip)

**Comment by rianlu** [comment]
> 编译了一套最新的 Intel 网卡驱动，适用于 macOS Ventura，您可以试试 [Wi-Fi.zip](https://github.com/Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH/files/11301114/Wi-Fi.zip) [Bluetooth.zip](https://github.com/Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH/files/11301115/Bluetooth.zip)

厉害，都正常驱动了，谢谢大佬！！！

**Comment by ken209** [comment]
怎么安装，求救。
