### ISSUE TITLE
关于版本选择问题

### ISSUE THREAD

**Issue by rianlu** [Fu-Yuxuan-hub/ASUS-TUF-GAMING-B460M-PLUS-HACKINTOSH#9]
你好，我看大佬最近更新了，查看readme似乎WiFi是不支持了吗
我目前的配置是：
i5-10500+ASUS TUF GAMING B460M-PLUS (WI-FI)重炮手主板，使用核显和自带无线网卡

目前所在系统是Monterey，可以再继续往上升级吗

**Comment by Stick-Study** [comment]
在 macOS 14 Sonoma 中，博通免驱卡已无法使用，其他都正常。Sonoma 的 Intel 网卡驱动用 Releases 里的z大的新版 Airportitlwm 即可正常使用

**Comment by rianlu** [comment]
> 在 macOS 14 Sonoma 中，博通免驱卡已无法使用，其他都正常。Sonoma 的 Intel 网卡驱动用 Releases 里的z大的新版 Airportitlwm 即可正常使用

好的，非常感谢！😘😘😘
